#
# BTstack example 'hid_host_demo' for ESP32 port
#
# Generated by /home/jewgad/esp/btstack/port/esp32
# On Sun Jun 26 15:23:34 2022

PROJECT_NAME := hid_host_demo

include $(IDF_PATH)/make/project.mk
